# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  code       :string
#  name       :string
#  price      :decimal(18, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_products_on_code  (code) UNIQUE
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

describe "Requests to /products", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Product. As you add validations to Product, be sure to
  # adjust the attributes here as well. The list could not be empty.
  let(:product) {create :product}

  let(:valid_attributes) {attributes_for(:product)}

  let(:invalid_attributes) do
    {name: ''}
  end

  describe "GET /index" do
    subject(:get_index) {get products_url}

    it "renders a successful response" do
      Product.create! valid_attributes
      get_index
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    subject(:get_show) {get product_url(id: product.to_param)}

    it "renders a successful response" do
      get_show
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    subject(:get_new) {get new_product_url}

    it "renders a successful response" do
      get_new
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    subject(:get_edit) {get edit_product_url(id: product.to_param)}

    it "render a successful response" do
      get_edit
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    subject(:post_create) do
      post products_url, params: { product: attributes }
    end

    context "with valid parameters" do
      let(:attributes) {valid_attributes}

      it "creates a new Product" do
        expect{post_create}.to change(Product, :count).by(1)
      end

      it "redirects to the created product" do
        post_create
        expect(response).to redirect_to product_url Product.last.to_param
      end
    end

    context "with invalid parameters" do
      let(:attributes) {invalid_attributes}

      it "does not create a new Product" do
        expect {post_create}.not_to change(Product, :count)
      end

      it "returns an unprocessable_entity response" do
        post_create
        expect(response).to have_http_status :unprocessable_entity
      end
    end
  end

  describe "PATCH /update" do
    subject(:patch_update) do
      patch product_url(id: product.to_param), params: { product: attributes }
    end

    context "with valid parameters" do
      let(:attributes) { {name: 'New value'} }

      it "updates the requested product" do
        patch_update
        product.reload
        expect(product.name).to eq 'New value'
      end

      it "redirects to the product" do
        patch_update
        product.reload
        expect(response).to redirect_to(product_url(id: product.to_param))
      end
    end

    context "with invalid parameters" do
      let(:attributes) {invalid_attributes}

      it "returns an unprocessable_entity response" do
        patch_update
        expect(response).to have_http_status :unprocessable_entity
      end
    end
  end

  describe "DELETE /destroy" do
    subject(:delete_destroy) {delete product_url(id: product.to_param)}

    it "destroys the requested product" do
      product
      expect {delete_destroy}.to change(Product, :count).by(-1)
    end

    it "redirects to the products list" do
      product
      delete_destroy
      expect(response).to redirect_to(products_url)
    end
  end
end
